# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import actor_pb2 as actor__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in actor_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ActorStub(object):
    """Интерфейс Actor
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetProbs = channel.unary_unary(
                '/infra.Actor/GetProbs',
                request_serializer=actor__pb2.GameStateRequest.SerializeToString,
                response_deserializer=actor__pb2.ActionProbsResponse.FromString,
                _registered_method=True)
        self.GetAvgProbs = channel.unary_unary(
                '/infra.Actor/GetAvgProbs',
                request_serializer=actor__pb2.GameStateRequest.SerializeToString,
                response_deserializer=actor__pb2.ActionProbsResponse.FromString,
                _registered_method=True)
        self.Train = channel.unary_unary(
                '/infra.Actor/Train',
                request_serializer=actor__pb2.TrainRequest.SerializeToString,
                response_deserializer=actor__pb2.TrainResponse.FromString,
                _registered_method=True)
        self.TrainAvg = channel.unary_unary(
                '/infra.Actor/TrainAvg',
                request_serializer=actor__pb2.TrainAvgRequest.SerializeToString,
                response_deserializer=actor__pb2.TrainResponse.FromString,
                _registered_method=True)
        self.Save = channel.unary_unary(
                '/infra.Actor/Save',
                request_serializer=actor__pb2.Empty.SerializeToString,
                response_deserializer=actor__pb2.Empty.FromString,
                _registered_method=True)


class ActorServicer(object):
    """Интерфейс Actor
    """

    def GetProbs(self, request, context):
        """Получить вероятности действий для игрока
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAvgProbs(self, request, context):
        """Получить вероятности действий для игрока
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Train(self, request, context):
        """Тренировать сеть
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TrainAvg(self, request, context):
        """Тренировать сеть
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Save(self, request, context):
        """Сохранить сеть
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ActorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetProbs': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProbs,
                    request_deserializer=actor__pb2.GameStateRequest.FromString,
                    response_serializer=actor__pb2.ActionProbsResponse.SerializeToString,
            ),
            'GetAvgProbs': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAvgProbs,
                    request_deserializer=actor__pb2.GameStateRequest.FromString,
                    response_serializer=actor__pb2.ActionProbsResponse.SerializeToString,
            ),
            'Train': grpc.unary_unary_rpc_method_handler(
                    servicer.Train,
                    request_deserializer=actor__pb2.TrainRequest.FromString,
                    response_serializer=actor__pb2.TrainResponse.SerializeToString,
            ),
            'TrainAvg': grpc.unary_unary_rpc_method_handler(
                    servicer.TrainAvg,
                    request_deserializer=actor__pb2.TrainAvgRequest.FromString,
                    response_serializer=actor__pb2.TrainResponse.SerializeToString,
            ),
            'Save': grpc.unary_unary_rpc_method_handler(
                    servicer.Save,
                    request_deserializer=actor__pb2.Empty.FromString,
                    response_serializer=actor__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'infra.Actor', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('infra.Actor', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Actor(object):
    """Интерфейс Actor
    """

    @staticmethod
    def GetProbs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/infra.Actor/GetProbs',
            actor__pb2.GameStateRequest.SerializeToString,
            actor__pb2.ActionProbsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAvgProbs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/infra.Actor/GetAvgProbs',
            actor__pb2.GameStateRequest.SerializeToString,
            actor__pb2.ActionProbsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Train(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/infra.Actor/Train',
            actor__pb2.TrainRequest.SerializeToString,
            actor__pb2.TrainResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TrainAvg(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/infra.Actor/TrainAvg',
            actor__pb2.TrainAvgRequest.SerializeToString,
            actor__pb2.TrainResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Save(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/infra.Actor/Save',
            actor__pb2.Empty.SerializeToString,
            actor__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
