services:
  neural:
    hostname: neural
    build:
      context: ./neural
      dockerfile: Dockerfile
    ports:
      - "1338:1338"
    volumes:
      - ./neural/checkpoints:/app/checkpoints
      - ./neural/tensorboard:/app/tensorboard
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  application:
    build:
      context: ./dcfr-go
      dockerfile: Dockerfile
    environment:
      - NEURAL_ADDR=neural:1338
    depends_on:
      - neural
    volumes:
      - ./data/go:/app/data
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  tensorboard:
    image: tensorflow/tensorflow:latest
    ports:
      - "6006:6006"
    volumes:
      - ./neural/tensorboard:/data/logs
    command: tensorboard --logdir=/data/logs --host=0.0.0.0
    depends_on:
      - neural
