// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: proto/infra/actor.proto

package infra

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Стадии игры
type GameStage int32

const (
	GameStage_PREFLOP  GameStage = 0
	GameStage_FLOP     GameStage = 1
	GameStage_TURN     GameStage = 2
	GameStage_RIVER    GameStage = 3
	GameStage_SHOWDOWN GameStage = 4
)

// Enum value maps for GameStage.
var (
	GameStage_name = map[int32]string{
		0: "PREFLOP",
		1: "FLOP",
		2: "TURN",
		3: "RIVER",
		4: "SHOWDOWN",
	}
	GameStage_value = map[string]int32{
		"PREFLOP":  0,
		"FLOP":     1,
		"TURN":     2,
		"RIVER":    3,
		"SHOWDOWN": 4,
	}
)

func (x GameStage) Enum() *GameStage {
	p := new(GameStage)
	*p = x
	return p
}

func (x GameStage) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GameStage) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_infra_actor_proto_enumTypes[0].Descriptor()
}

func (GameStage) Type() protoreflect.EnumType {
	return &file_proto_infra_actor_proto_enumTypes[0]
}

func (x GameStage) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GameStage.Descriptor instead.
func (GameStage) EnumDescriptor() ([]byte, []int) {
	return file_proto_infra_actor_proto_rawDescGZIP(), []int{0}
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_proto_infra_actor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_infra_actor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_infra_actor_proto_rawDescGZIP(), []int{0}
}

// Определение карты
// Состояние игры
type GameState struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ActivePlayersMask []int32                `protobuf:"varint,1,rep,packed,name=active_players_mask,json=activePlayersMask,proto3" json:"active_players_mask,omitempty"`                                                    // Маска активных игроков
	PlayersPots       []int32                `protobuf:"varint,2,rep,packed,name=players_pots,json=playersPots,proto3" json:"players_pots,omitempty"`                                                                        // Банки игроков
	Stakes            []int32                `protobuf:"varint,3,rep,packed,name=stakes,proto3" json:"stakes,omitempty"`                                                                                                     // Текущие ставки игроков
	LegalActions      map[int32]bool         `protobuf:"bytes,4,rep,name=legal_actions,json=legalActions,proto3" json:"legal_actions,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"` // Доступные действия (ключ - действие, значение - всегда true)
	Stage             GameStage              `protobuf:"varint,5,opt,name=stage,proto3,enum=infra.GameStage" json:"stage,omitempty"`                                                                                         // Текущая стадия игры
	CurrentPlayer     int32                  `protobuf:"varint,6,opt,name=current_player,json=currentPlayer,proto3" json:"current_player,omitempty"`                                                                         // ID текущего игрока
	PublicCards       []int32                `protobuf:"varint,7,rep,packed,name=public_cards,json=publicCards,proto3" json:"public_cards,omitempty"`                                                                        // Общие карты на столе
	PrivateCards      []int32                `protobuf:"varint,8,rep,packed,name=private_cards,json=privateCards,proto3" json:"private_cards,omitempty"`                                                                     // Карты текущего игрока
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GameState) Reset() {
	*x = GameState{}
	mi := &file_proto_infra_actor_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameState) ProtoMessage() {}

func (x *GameState) ProtoReflect() protoreflect.Message {
	mi := &file_proto_infra_actor_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameState.ProtoReflect.Descriptor instead.
func (*GameState) Descriptor() ([]byte, []int) {
	return file_proto_infra_actor_proto_rawDescGZIP(), []int{1}
}

func (x *GameState) GetActivePlayersMask() []int32 {
	if x != nil {
		return x.ActivePlayersMask
	}
	return nil
}

func (x *GameState) GetPlayersPots() []int32 {
	if x != nil {
		return x.PlayersPots
	}
	return nil
}

func (x *GameState) GetStakes() []int32 {
	if x != nil {
		return x.Stakes
	}
	return nil
}

func (x *GameState) GetLegalActions() map[int32]bool {
	if x != nil {
		return x.LegalActions
	}
	return nil
}

func (x *GameState) GetStage() GameStage {
	if x != nil {
		return x.Stage
	}
	return GameStage_PREFLOP
}

func (x *GameState) GetCurrentPlayer() int32 {
	if x != nil {
		return x.CurrentPlayer
	}
	return 0
}

func (x *GameState) GetPublicCards() []int32 {
	if x != nil {
		return x.PublicCards
	}
	return nil
}

func (x *GameState) GetPrivateCards() []int32 {
	if x != nil {
		return x.PrivateCards
	}
	return nil
}

// Тренировочный сэмпл
type StateSample struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GameState     *GameState             `protobuf:"bytes,1,opt,name=game_state,json=gameState,proto3" json:"game_state,omitempty"`                                                         // Состояние игры
	Regrets       map[int32]float32      `protobuf:"bytes,2,rep,name=regrets,proto3" json:"regrets,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"fixed32,2,opt,name=value"` // Сожаления для действий (Action -> float32)
	Iteration     int32                  `protobuf:"varint,3,opt,name=iteration,proto3" json:"iteration,omitempty"`                                                                         // Номер итерации
	LstmContextH  []float32              `protobuf:"fixed32,4,rep,packed,name=lstm_context_h,json=lstmContextH,proto3" json:"lstm_context_h,omitempty"`
	LstmContextC  []float32              `protobuf:"fixed32,5,rep,packed,name=lstm_context_c,json=lstmContextC,proto3" json:"lstm_context_c,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StateSample) Reset() {
	*x = StateSample{}
	mi := &file_proto_infra_actor_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StateSample) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateSample) ProtoMessage() {}

func (x *StateSample) ProtoReflect() protoreflect.Message {
	mi := &file_proto_infra_actor_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateSample.ProtoReflect.Descriptor instead.
func (*StateSample) Descriptor() ([]byte, []int) {
	return file_proto_infra_actor_proto_rawDescGZIP(), []int{2}
}

func (x *StateSample) GetGameState() *GameState {
	if x != nil {
		return x.GameState
	}
	return nil
}

func (x *StateSample) GetRegrets() map[int32]float32 {
	if x != nil {
		return x.Regrets
	}
	return nil
}

func (x *StateSample) GetIteration() int32 {
	if x != nil {
		return x.Iteration
	}
	return 0
}

func (x *StateSample) GetLstmContextH() []float32 {
	if x != nil {
		return x.LstmContextH
	}
	return nil
}

func (x *StateSample) GetLstmContextC() []float32 {
	if x != nil {
		return x.LstmContextC
	}
	return nil
}

type GameSample struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Samples       []*StateSample         `protobuf:"bytes,1,rep,name=samples,proto3" json:"samples,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameSample) Reset() {
	*x = GameSample{}
	mi := &file_proto_infra_actor_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameSample) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameSample) ProtoMessage() {}

func (x *GameSample) ProtoReflect() protoreflect.Message {
	mi := &file_proto_infra_actor_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameSample.ProtoReflect.Descriptor instead.
func (*GameSample) Descriptor() ([]byte, []int) {
	return file_proto_infra_actor_proto_rawDescGZIP(), []int{3}
}

func (x *GameSample) GetSamples() []*StateSample {
	if x != nil {
		return x.Samples
	}
	return nil
}

type CFRState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GameState     *GameState             `protobuf:"bytes,1,opt,name=game_state,json=gameState,proto3" json:"game_state,omitempty"`
	LstmContextH  []float32              `protobuf:"fixed32,2,rep,packed,name=lstm_context_h,json=lstmContextH,proto3" json:"lstm_context_h,omitempty"`
	LstmContextC  []float32              `protobuf:"fixed32,3,rep,packed,name=lstm_context_c,json=lstmContextC,proto3" json:"lstm_context_c,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CFRState) Reset() {
	*x = CFRState{}
	mi := &file_proto_infra_actor_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CFRState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CFRState) ProtoMessage() {}

func (x *CFRState) ProtoReflect() protoreflect.Message {
	mi := &file_proto_infra_actor_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CFRState.ProtoReflect.Descriptor instead.
func (*CFRState) Descriptor() ([]byte, []int) {
	return file_proto_infra_actor_proto_rawDescGZIP(), []int{4}
}

func (x *CFRState) GetGameState() *GameState {
	if x != nil {
		return x.GameState
	}
	return nil
}

func (x *CFRState) GetLstmContextH() []float32 {
	if x != nil {
		return x.LstmContextH
	}
	return nil
}

func (x *CFRState) GetLstmContextC() []float32 {
	if x != nil {
		return x.LstmContextC
	}
	return nil
}

type ActionProbsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	States        []*CFRState            `protobuf:"bytes,1,rep,name=states,proto3" json:"states,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActionProbsRequest) Reset() {
	*x = ActionProbsRequest{}
	mi := &file_proto_infra_actor_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionProbsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionProbsRequest) ProtoMessage() {}

func (x *ActionProbsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_infra_actor_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionProbsRequest.ProtoReflect.Descriptor instead.
func (*ActionProbsRequest) Descriptor() ([]byte, []int) {
	return file_proto_infra_actor_proto_rawDescGZIP(), []int{5}
}

func (x *ActionProbsRequest) GetStates() []*CFRState {
	if x != nil {
		return x.States
	}
	return nil
}

// Ответ с вероятностями действий
type ActionProbsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Responses     []*ProbsResponse       `protobuf:"bytes,1,rep,name=responses,proto3" json:"responses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActionProbsResponse) Reset() {
	*x = ActionProbsResponse{}
	mi := &file_proto_infra_actor_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionProbsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionProbsResponse) ProtoMessage() {}

func (x *ActionProbsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_infra_actor_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionProbsResponse.ProtoReflect.Descriptor instead.
func (*ActionProbsResponse) Descriptor() ([]byte, []int) {
	return file_proto_infra_actor_proto_rawDescGZIP(), []int{6}
}

func (x *ActionProbsResponse) GetResponses() []*ProbsResponse {
	if x != nil {
		return x.Responses
	}
	return nil
}

type ProbsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActionProbs   map[int32]float32      `protobuf:"bytes,1,rep,name=action_probs,json=actionProbs,proto3" json:"action_probs,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"fixed32,2,opt,name=value"` // Карта вероятностей действий
	LstmContextH  []float32              `protobuf:"fixed32,2,rep,packed,name=lstm_context_h,json=lstmContextH,proto3" json:"lstm_context_h,omitempty"`
	LstmContextC  []float32              `protobuf:"fixed32,3,rep,packed,name=lstm_context_c,json=lstmContextC,proto3" json:"lstm_context_c,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProbsResponse) Reset() {
	*x = ProbsResponse{}
	mi := &file_proto_infra_actor_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProbsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProbsResponse) ProtoMessage() {}

func (x *ProbsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_infra_actor_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProbsResponse.ProtoReflect.Descriptor instead.
func (*ProbsResponse) Descriptor() ([]byte, []int) {
	return file_proto_infra_actor_proto_rawDescGZIP(), []int{7}
}

func (x *ProbsResponse) GetActionProbs() map[int32]float32 {
	if x != nil {
		return x.ActionProbs
	}
	return nil
}

func (x *ProbsResponse) GetLstmContextH() []float32 {
	if x != nil {
		return x.LstmContextH
	}
	return nil
}

func (x *ProbsResponse) GetLstmContextC() []float32 {
	if x != nil {
		return x.LstmContextC
	}
	return nil
}

// Запрос на тренировку
type TrainRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CurrentPlayer int32                  `protobuf:"varint,1,opt,name=current_player,json=currentPlayer,proto3" json:"current_player,omitempty"`
	GameSamples   []*GameSample          `protobuf:"bytes,2,rep,name=game_samples,json=gameSamples,proto3" json:"game_samples,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrainRequest) Reset() {
	*x = TrainRequest{}
	mi := &file_proto_infra_actor_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrainRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrainRequest) ProtoMessage() {}

func (x *TrainRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_infra_actor_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrainRequest.ProtoReflect.Descriptor instead.
func (*TrainRequest) Descriptor() ([]byte, []int) {
	return file_proto_infra_actor_proto_rawDescGZIP(), []int{8}
}

func (x *TrainRequest) GetCurrentPlayer() int32 {
	if x != nil {
		return x.CurrentPlayer
	}
	return 0
}

func (x *TrainRequest) GetGameSamples() []*GameSample {
	if x != nil {
		return x.GameSamples
	}
	return nil
}

type TrainResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Loss          float32                `protobuf:"fixed32,1,opt,name=loss,proto3" json:"loss,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrainResponse) Reset() {
	*x = TrainResponse{}
	mi := &file_proto_infra_actor_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrainResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrainResponse) ProtoMessage() {}

func (x *TrainResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_infra_actor_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrainResponse.ProtoReflect.Descriptor instead.
func (*TrainResponse) Descriptor() ([]byte, []int) {
	return file_proto_infra_actor_proto_rawDescGZIP(), []int{9}
}

func (x *TrainResponse) GetLoss() float32 {
	if x != nil {
		return x.Loss
	}
	return 0
}

var File_proto_infra_actor_proto protoreflect.FileDescriptor

const file_proto_infra_actor_proto_rawDesc = "" +
	"\n" +
	"\x17proto/infra/actor.proto\x12\x05infra\"\a\n" +
	"\x05Empty\"\x97\x03\n" +
	"\tGameState\x12.\n" +
	"\x13active_players_mask\x18\x01 \x03(\x05R\x11activePlayersMask\x12!\n" +
	"\fplayers_pots\x18\x02 \x03(\x05R\vplayersPots\x12\x16\n" +
	"\x06stakes\x18\x03 \x03(\x05R\x06stakes\x12G\n" +
	"\rlegal_actions\x18\x04 \x03(\v2\".infra.GameState.LegalActionsEntryR\flegalActions\x12&\n" +
	"\x05stage\x18\x05 \x01(\x0e2\x10.infra.GameStageR\x05stage\x12%\n" +
	"\x0ecurrent_player\x18\x06 \x01(\x05R\rcurrentPlayer\x12!\n" +
	"\fpublic_cards\x18\a \x03(\x05R\vpublicCards\x12#\n" +
	"\rprivate_cards\x18\b \x03(\x05R\fprivateCards\x1a?\n" +
	"\x11LegalActionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\bR\x05value:\x028\x01\"\x9f\x02\n" +
	"\vStateSample\x12/\n" +
	"\n" +
	"game_state\x18\x01 \x01(\v2\x10.infra.GameStateR\tgameState\x129\n" +
	"\aregrets\x18\x02 \x03(\v2\x1f.infra.StateSample.RegretsEntryR\aregrets\x12\x1c\n" +
	"\titeration\x18\x03 \x01(\x05R\titeration\x12$\n" +
	"\x0elstm_context_h\x18\x04 \x03(\x02R\flstmContextH\x12$\n" +
	"\x0elstm_context_c\x18\x05 \x03(\x02R\flstmContextC\x1a:\n" +
	"\fRegretsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x02R\x05value:\x028\x01\":\n" +
	"\n" +
	"GameSample\x12,\n" +
	"\asamples\x18\x01 \x03(\v2\x12.infra.StateSampleR\asamples\"\x87\x01\n" +
	"\bCFRState\x12/\n" +
	"\n" +
	"game_state\x18\x01 \x01(\v2\x10.infra.GameStateR\tgameState\x12$\n" +
	"\x0elstm_context_h\x18\x02 \x03(\x02R\flstmContextH\x12$\n" +
	"\x0elstm_context_c\x18\x03 \x03(\x02R\flstmContextC\"=\n" +
	"\x12ActionProbsRequest\x12'\n" +
	"\x06states\x18\x01 \x03(\v2\x0f.infra.CFRStateR\x06states\"I\n" +
	"\x13ActionProbsResponse\x122\n" +
	"\tresponses\x18\x01 \x03(\v2\x14.infra.ProbsResponseR\tresponses\"\xe5\x01\n" +
	"\rProbsResponse\x12H\n" +
	"\faction_probs\x18\x01 \x03(\v2%.infra.ProbsResponse.ActionProbsEntryR\vactionProbs\x12$\n" +
	"\x0elstm_context_h\x18\x02 \x03(\x02R\flstmContextH\x12$\n" +
	"\x0elstm_context_c\x18\x03 \x03(\x02R\flstmContextC\x1a>\n" +
	"\x10ActionProbsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x02R\x05value:\x028\x01\"k\n" +
	"\fTrainRequest\x12%\n" +
	"\x0ecurrent_player\x18\x01 \x01(\x05R\rcurrentPlayer\x124\n" +
	"\fgame_samples\x18\x02 \x03(\v2\x11.infra.GameSampleR\vgameSamples\"#\n" +
	"\rTrainResponse\x12\x12\n" +
	"\x04loss\x18\x01 \x01(\x02R\x04loss*E\n" +
	"\tGameStage\x12\v\n" +
	"\aPREFLOP\x10\x00\x12\b\n" +
	"\x04FLOP\x10\x01\x12\b\n" +
	"\x04TURN\x10\x02\x12\t\n" +
	"\x05RIVER\x10\x03\x12\f\n" +
	"\bSHOWDOWN\x10\x042\xcf\x01\n" +
	"\x05Actor\x12C\n" +
	"\bGetProbs\x12\x19.infra.ActionProbsRequest\x1a\x1a.infra.ActionProbsResponse\"\x00\x124\n" +
	"\x05Train\x12\x13.infra.TrainRequest\x1a\x14.infra.TrainResponse\"\x00\x12$\n" +
	"\x04Save\x12\f.infra.Empty\x1a\f.infra.Empty\"\x00\x12%\n" +
	"\x05Reset\x12\f.infra.Empty\x1a\f.infra.Empty\"\x00B\tZ\a.;infrab\x06proto3"

var (
	file_proto_infra_actor_proto_rawDescOnce sync.Once
	file_proto_infra_actor_proto_rawDescData []byte
)

func file_proto_infra_actor_proto_rawDescGZIP() []byte {
	file_proto_infra_actor_proto_rawDescOnce.Do(func() {
		file_proto_infra_actor_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_infra_actor_proto_rawDesc), len(file_proto_infra_actor_proto_rawDesc)))
	})
	return file_proto_infra_actor_proto_rawDescData
}

var file_proto_infra_actor_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_infra_actor_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_proto_infra_actor_proto_goTypes = []any{
	(GameStage)(0),              // 0: infra.GameStage
	(*Empty)(nil),               // 1: infra.Empty
	(*GameState)(nil),           // 2: infra.GameState
	(*StateSample)(nil),         // 3: infra.StateSample
	(*GameSample)(nil),          // 4: infra.GameSample
	(*CFRState)(nil),            // 5: infra.CFRState
	(*ActionProbsRequest)(nil),  // 6: infra.ActionProbsRequest
	(*ActionProbsResponse)(nil), // 7: infra.ActionProbsResponse
	(*ProbsResponse)(nil),       // 8: infra.ProbsResponse
	(*TrainRequest)(nil),        // 9: infra.TrainRequest
	(*TrainResponse)(nil),       // 10: infra.TrainResponse
	nil,                         // 11: infra.GameState.LegalActionsEntry
	nil,                         // 12: infra.StateSample.RegretsEntry
	nil,                         // 13: infra.ProbsResponse.ActionProbsEntry
}
var file_proto_infra_actor_proto_depIdxs = []int32{
	11, // 0: infra.GameState.legal_actions:type_name -> infra.GameState.LegalActionsEntry
	0,  // 1: infra.GameState.stage:type_name -> infra.GameStage
	2,  // 2: infra.StateSample.game_state:type_name -> infra.GameState
	12, // 3: infra.StateSample.regrets:type_name -> infra.StateSample.RegretsEntry
	3,  // 4: infra.GameSample.samples:type_name -> infra.StateSample
	2,  // 5: infra.CFRState.game_state:type_name -> infra.GameState
	5,  // 6: infra.ActionProbsRequest.states:type_name -> infra.CFRState
	8,  // 7: infra.ActionProbsResponse.responses:type_name -> infra.ProbsResponse
	13, // 8: infra.ProbsResponse.action_probs:type_name -> infra.ProbsResponse.ActionProbsEntry
	4,  // 9: infra.TrainRequest.game_samples:type_name -> infra.GameSample
	6,  // 10: infra.Actor.GetProbs:input_type -> infra.ActionProbsRequest
	9,  // 11: infra.Actor.Train:input_type -> infra.TrainRequest
	1,  // 12: infra.Actor.Save:input_type -> infra.Empty
	1,  // 13: infra.Actor.Reset:input_type -> infra.Empty
	7,  // 14: infra.Actor.GetProbs:output_type -> infra.ActionProbsResponse
	10, // 15: infra.Actor.Train:output_type -> infra.TrainResponse
	1,  // 16: infra.Actor.Save:output_type -> infra.Empty
	1,  // 17: infra.Actor.Reset:output_type -> infra.Empty
	14, // [14:18] is the sub-list for method output_type
	10, // [10:14] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_proto_infra_actor_proto_init() }
func file_proto_infra_actor_proto_init() {
	if File_proto_infra_actor_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_infra_actor_proto_rawDesc), len(file_proto_infra_actor_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_infra_actor_proto_goTypes,
		DependencyIndexes: file_proto_infra_actor_proto_depIdxs,
		EnumInfos:         file_proto_infra_actor_proto_enumTypes,
		MessageInfos:      file_proto_infra_actor_proto_msgTypes,
	}.Build()
	File_proto_infra_actor_proto = out.File
	file_proto_infra_actor_proto_goTypes = nil
	file_proto_infra_actor_proto_depIdxs = nil
}
